### PR TITLE
Django 5.0, py3.12 and pre-commit

### PR DESCRIPTION
**Pull request by tim-schilling**
- Add Django 5.0
- Drop Django 4.0 and 4.1
- Drop python 3.6, 3.7
- Replace pep8 and pytest-pep8 with pre-commit with flake8 and autopep (I left off black for now, but I recommend adding that or ruff)

### CODE REVIEW

**Comment by stevejalim** [comment]
@tim-schilling Thanks for this - I had another branch in flight locally that moves us to ruff, but I'll make sure I add pre-commit as per your suggestions. Sorry not to just merge this as-is, because it's a valid contribution

**Comment by tim-schilling** [comment]
No worries!

**Comment by tim-schilling** [comment]
I think [0ca824e](https://github.com/stevejalim/django-csp/pull/1/commits/0ca824ee38fee85af6bcd139e3b633a3a9ea4959) is still worthwhile

**Comment by stevejalim** [comment]
@tim-schilling Absolutely - that's done in spirit along with a move to GHA over in https://github.com/mozilla/django-csp/commit/3eadb4c785c78e1b5ad0e178e7eb13d88572f6fb

**Comment by tim-schilling** [comment]
Ah, I missed that. Excellent!

**Pull request closed without merging**
